; ==========================================================
; VoltGuard PlatformIO Configuration File (Firmware folder)
; ==========================================================

[platformio]
; Tell PlatformIO to compile the sub-folder directly
src_dir = VoltGuard_ESP32

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Compiler options
build_flags = 
    -DCORE_DEBUG_LEVEL=3

; Library Dependencies
lib_deps =
    mandulaj/PZEM-004T-v30 @ ^1.1.2
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
